# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "almalinux/8"
    config.vagrant.plugins = ["vagrant-vbguest", "vagrant-hostmanager"]
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true
    config.vbguest.auto_update = false 
    
    config.vm.define "master" do |master|
      master.vm.hostname = "master.training.home"
      master.vm.network "private_network", ip: "192.168.225.100"
      master.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "4094"
        vb.cpus = "4"
      end

      master.vm.provision "shell", :path => "scripts/init.sh"
      master.vm.provision "shell", :path => "scripts/cri-o_install.sh"
      master.vm.provision "shell", :path => "scripts/setup-k8s.sh"
      master.vm.provision "shell", :path => "scripts/master.sh"
    end

  (1..3).each do |n|
    config.vm.define "worker-#{n}" do |worker|
      worker.vm.hostname = "worker-#{n}.training.home"
      worker.vm.network "private_network", ip: "192.168.225.10#{n}"
      worker.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.cpus = 2
        vb.memory = 4096]
        vb.customize ['createmedium', 'disk', '--filename', "k8s_training#{n}.vmdk", '--format', 'VDI', '--size', 10 * 1024]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "k8s_training#{n}.vmdk"]
      end  

      worker.vm.provision "shell", :path => "scripts/init.sh"
      worker.vm.provision "shell", :path => "scripts/cri-o_install.sh"
      worker.vm.provision "shell", :path => "scripts/setup-k8s.sh"
      worker.vm.provision "shell", :path => "scripts/worker.sh"
      end
    end
end
  